/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tecnologo
 */
public class AltaEspectaculo extends javax.swing.JFrame {

    /**
     * Creates new form AltaEspectaculo
     */
    public AltaEspectaculo() {
        initComponents();
        List<String> lPlataformas = new ArrayList<String>();
        lPlataformas.add("--Seleccione Plataforma--");
        Fabrica.getCtrlEspectaculos();
        List<DtPlataforma> dtPlataforma = Fabrica.getCtrlEspectaculos().listarPlataformas();
        for (DtPlataforma iterator :dtPlataforma){
            lPlataformas.add(iterator.getNombre());
        }
        this.cbListaPlataformas.setModel(new DefaultComboBoxModel(lPlataformas.toArray()));
        
        List<String> lArtistas = new ArrayList<String>();
        lArtistas.add("--Seleccione Artista--");
        List<DtArtista> dtArtista = Fabrica.getCrlUsuarios().getArtistas();
        for (DtArtista iterator :dtArtista){
            lArtistas.add(iterator.getNickname());
        }
        this.cbListaArtista.setModel(new DefaultComboBoxModel(lArtistas.toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNombre = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        cbListaPlataformas = new javax.swing.JComboBox<>();
        cbDiaEspectaculo = new javax.swing.JComboBox<>();
        cbListaArtista = new javax.swing.JComboBox<>();
        cbMesEspectaculo = new javax.swing.JComboBox<>();
        lbListaArtistas = new javax.swing.JLabel();
        cbAnioEspectaculo = new javax.swing.JComboBox<>();
        tbNombre = new javax.swing.JTextField();
        btCancelar = new javax.swing.JButton();
        btConfirmar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbListaPlataformas = new javax.swing.JLabel();
        tbDuracion = new javax.swing.JTextField();
        lbDuracion = new javax.swing.JLabel();
        lbExpecatdoresMinimos = new javax.swing.JLabel();
        tbExpectadoresMin = new javax.swing.JTextField();
        tbCosto = new javax.swing.JTextField();
        cbDiaAlta = new javax.swing.JComboBox<>();
        cbMesAlta = new javax.swing.JComboBox<>();
        lbFechaAlta = new javax.swing.JLabel();
        cbAnioAlta = new javax.swing.JComboBox<>();
        lbCosto = new javax.swing.JLabel();
        tbExpectadoresMax = new javax.swing.JTextField();
        tbDescripcion = new javax.swing.JTextField();
        lbDescripcion = new javax.swing.JLabel();
        lbExpectadoresMaximo = new javax.swing.JLabel();
        lbIngreseDatos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbNombre.setText("Nombre");

        lbFecha.setText("Fecha");

        cbListaPlataformas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbListaPlataformasItemStateChanged(evt);
            }
        });
        cbListaPlataformas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbListaPlataformasActionPerformed(evt);
            }
        });

        cbMesEspectaculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesEspectaculoActionPerformed(evt);
            }
        });

        lbListaArtistas.setText("Listar Artista");

        cbAnioEspectaculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnioEspectaculoActionPerformed(evt);
            }
        });

        tbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNombreActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        jLabel2.setText("Alta Espectaculo");

        lbListaPlataformas.setText("Listar Plataformas");

        lbDuracion.setText("Duracion");

        lbExpecatdoresMinimos.setText("Expectadores Minimos");

        tbExpectadoresMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbExpectadoresMinActionPerformed(evt);
            }
        });

        tbCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCostoActionPerformed(evt);
            }
        });

        cbMesAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesAltaActionPerformed(evt);
            }
        });

        lbFechaAlta.setText("Fecha de Alta");

        cbAnioAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnioAltaActionPerformed(evt);
            }
        });

        lbCosto.setText("Costo");

        tbExpectadoresMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbExpectadoresMaxActionPerformed(evt);
            }
        });

        lbDescripcion.setText("Descripcion");

        lbExpectadoresMaximo.setText("Expectadores Maximo");

        lbIngreseDatos.setText("Ingrese datos del Espectaculo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(196, 196, 196))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btConfirmar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNombre)
                                    .addComponent(lbCosto)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbFecha)
                                            .addComponent(lbDuracion)
                                            .addComponent(lbListaArtistas)
                                            .addComponent(lbListaPlataformas))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbListaPlataformas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbListaArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbDiaEspectaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbMesEspectaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbAnioEspectaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbDiaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbMesAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbAnioAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tbDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 118, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbFechaAlta)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbExpecatdoresMinimos)
                                    .addComponent(lbDescripcion)
                                    .addComponent(lbExpectadoresMaximo, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbExpectadoresMin, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbExpectadoresMax, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbIngreseDatos))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbListaPlataformas)
                    .addComponent(cbListaPlataformas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbListaArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbListaArtistas))
                .addGap(21, 21, 21)
                .addComponent(lbIngreseDatos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDiaEspectaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMesEspectaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAnioEspectaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDiaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMesAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAnioAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFechaAlta))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btConfirmar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDescripcion)
                            .addComponent(tbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDuracion)
                            .addComponent(tbDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbExpecatdoresMinimos)
                            .addComponent(tbExpectadoresMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbExpectadoresMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbExpectadoresMaximo))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCosto)
                            .addComponent(tbCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbListaPlataformasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbListaPlataformasItemStateChanged

    }//GEN-LAST:event_cbListaPlataformasItemStateChanged

    private void cbListaPlataformasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbListaPlataformasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbListaPlataformasActionPerformed

    private void cbMesEspectaculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesEspectaculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesEspectaculoActionPerformed

    private void cbAnioEspectaculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnioEspectaculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAnioEspectaculoActionPerformed

    private void tbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNombreActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
            // TODO add your handling code here:    
        if(Fabrica.getCtrlEspectaculos().existeEspectaculo(tbNombre.getText()))
        {
            JOptionPane.showMessageDialog(null, "Ya existe", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
        }
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void tbExpectadoresMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbExpectadoresMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbExpectadoresMinActionPerformed

    private void tbCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbCostoActionPerformed

    private void cbMesAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesAltaActionPerformed

    private void cbAnioAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnioAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAnioAltaActionPerformed

    private void tbExpectadoresMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbExpectadoresMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbExpectadoresMaxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaEspectaculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaEspectaculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaEspectaculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaEspectaculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaEspectaculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JComboBox<String> cbAnioAlta;
    private javax.swing.JComboBox<String> cbAnioEspectaculo;
    private javax.swing.JComboBox<String> cbDiaAlta;
    private javax.swing.JComboBox<String> cbDiaEspectaculo;
    private javax.swing.JComboBox<String> cbListaArtista;
    private javax.swing.JComboBox<String> cbListaPlataformas;
    private javax.swing.JComboBox<String> cbMesAlta;
    private javax.swing.JComboBox<String> cbMesEspectaculo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbCosto;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbDuracion;
    private javax.swing.JLabel lbExpecatdoresMinimos;
    private javax.swing.JLabel lbExpectadoresMaximo;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbFechaAlta;
    private javax.swing.JLabel lbIngreseDatos;
    private javax.swing.JLabel lbListaArtistas;
    private javax.swing.JLabel lbListaPlataformas;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JTextField tbCosto;
    private javax.swing.JTextField tbDescripcion;
    private javax.swing.JTextField tbDuracion;
    private javax.swing.JTextField tbExpectadoresMax;
    private javax.swing.JTextField tbExpectadoresMin;
    private javax.swing.JTextField tbNombre;
    // End of variables declaration//GEN-END:variables
}
