/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author tecnologo
 */
public class ConsultaEspectaculo extends javax.swing.JFrame {
    private List<DtEspectaculo> espectaculos=new ArrayList<>();
    /**
     * Creates new form ConsultaEspectaculo
     */
    public ConsultaEspectaculo() {
        initComponents();
       
        //listaPlataformas
        List<String> lPlataformas = new ArrayList<>();
        lPlataformas.add("--Seleccione Plataforma--");
        //Fabrica.getCtrlEspectaculos();
        List<DtPlataforma> dtPlataforma;
        dtPlataforma = Fabrica.getCtrlEspectaculos().listarPlataformas();
        dtPlataforma.forEach(iterator -> {
            lPlataformas.add(iterator.getNombre());
        });
        this.cbPlataformas.setModel(new DefaultComboBoxModel(lPlataformas.toArray()));    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbPlataforma = new javax.swing.JLabel();
        cbPlataformas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        LbEspectaculo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFunciones = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPaquetes = new javax.swing.JTable();
        btSalir = new javax.swing.JButton();
        LbFunciones = new javax.swing.JLabel();
        LbPaquetes = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbEspectaculo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbPlataforma.setText("Plataformas");

        cbPlataformas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlataformasActionPerformed(evt);
            }
        });

        jLabel2.setText("Consulta Espectaculo");

        LbEspectaculo.setText("Espectaculo");

        tbFunciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbFunciones);

        tbPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPaquetesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPaquetes);

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        LbFunciones.setText("Funciones");

        LbPaquetes.setText("Paquetes");

        tbEspectaculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbEspectaculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEspectaculoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbEspectaculo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbPlataforma)
                                .addGap(20, 20, 20)
                                .addComponent(cbPlataformas, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LbFunciones)
                            .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbPaquetes)
                            .addComponent(LbEspectaculo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPlataformas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPlataforma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LbEspectaculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbFunciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbPaquetes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Principal p = new Principal();
        p.setVisible(true);

    }//GEN-LAST:event_btSalirActionPerformed

    private void cbPlataformasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlataformasActionPerformed
        // TODO add your handling code here:
        //listaEspectaculo
        espectaculos=Fabrica.getCtrlEspectaculos().listarEspectaculos(cbPlataformas.getSelectedItem().toString());
        
        String matris[][] = new String [espectaculos.size()][7];
        
        for(int i=0; i<espectaculos.size(); i++)
        {

            matris [i][0]=espectaculos.get(i).getNombre();
            matris [i][1]=espectaculos.get(i).getDescripcion();
            matris [i][2]=Integer.toString(espectaculos.get(i).getCantidadMaximaEspectadores());
            matris [i][3]=Integer.toString(espectaculos.get(i).getCantidadMinimaEspectadores());
            matris [i][4]=Float.toString(espectaculos.get(i).getCosto());
            matris [i][5]=espectaculos.get(i).getUrl();
            matris [i][6]=espectaculos.get(i).getFechaDeRegistro().toString();

        }
        tbEspectaculo.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Nombre", "Descripcion", "Esp Max", "Esp Min", "Costo", "URL", "Fecha de Registro"
            }
        ));
    }//GEN-LAST:event_cbPlataformasActionPerformed

    private void tbPaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPaquetesMouseClicked
        // TODO add your handling code here:
        int index = tbPaquetes.getSelectedRow();
        
    }//GEN-LAST:event_tbPaquetesMouseClicked

    private void tbEspectaculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEspectaculoMouseClicked
        // TODO add your handling code here:
        int indexE = tbEspectaculo.getSelectedRow();
        List<DtPaqueteDeEspectaculos> paquetes=Fabrica.getCrlUsuarios().listarPaquetesEspectaculosDeArtista("", espectaculos.get(indexE).getNombre());
        List<DtFuncion> funciones=Fabrica.getCrlUsuarios().listarFuncionesEspectaculosDeArtista("", espectaculos.get(indexE).getNombre());
        DtPlataforma plataforma=Fabrica.getCrlUsuarios().plataformaEspectaculosDeArtista("", espectaculos.get(indexE).getNombre());
        String matrisP[][] = new String [paquetes.size()][5];
        String matrisF[][] = new String [funciones.size()][2];
        
        for(int i=0; i<funciones.size(); i++)
        {

            matrisF [i][0]=funciones.get(i).getNombre();
            matrisF [i][1]=funciones.get(i).getHoraInicio().toString();
            
        }
        
        tbFunciones.setModel(new javax.swing.table.DefaultTableModel(
            matrisF,
            new String [] {
                "Nombre ", "Fecha y hora"
            }
        ));
        
        for(int i=0; i<paquetes.size(); i++)
        {

            matrisP [i][0]=paquetes.get(i).getNombre();
            matrisP [i][1]=paquetes.get(i).getDescripcion();
            matrisP [i][2]=paquetes.get(i).getFechaInicio().toString();
            matrisP [i][3]=paquetes.get(i).getFechaFin().toString();
            matrisP [i][4]=Float.toString(paquetes.get(i).getDescuento());
        }
        
        tbPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            matrisP,
            new String [] {
                "Nombre", "Descripcion", "Inicio", "Fin", "Descuento"
            }
        ));
    }//GEN-LAST:event_tbEspectaculoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaEspectaculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaEspectaculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaEspectaculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaEspectaculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaEspectaculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbEspectaculo;
    private javax.swing.JLabel LbFunciones;
    private javax.swing.JLabel LbPaquetes;
    private javax.swing.JButton btSalir;
    private javax.swing.JComboBox<String> cbPlataformas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbPlataforma;
    private javax.swing.JTable tbEspectaculo;
    private javax.swing.JTable tbFunciones;
    private javax.swing.JTable tbPaquetes;
    // End of variables declaration//GEN-END:variables
}
