/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author tecnologo
 */
public class ListarEspectadores extends javax.swing.JFrame {
    private List<DtEspectador> espectadores=new ArrayList<DtEspectador>();
    
    /**
     * Creates new form ListarEspectadores
     */
    public ListarEspectadores() {
        initComponents();
        espectadores=Fabrica.getCrlUsuarios().getEspectadores();
        String matris[][] = new String [espectadores.size()][6];
        for(int i=0; i<espectadores.size(); i++)
        {
            matris [i][0]=espectadores.get(i).getNombre();
            matris [i][1]=espectadores.get(i).getApellido();
            matris [i][2]=espectadores.get(i).getNickname();
            matris [i][3]=espectadores.get(i).getCorreo();
            matris [i][4]=espectadores.get(i).getFechaNacimiento().toString();
            matris [i][5]=Integer.toString(espectadores.get(i).getCanjeables());
        }
        tEspectadores.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Nombre", "Apellido", "Nickname", "Correo Electonico", "Fecha de Nacimiento", "Registros sin gastar"
            }
        ));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tEspectadores = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tRegistros = new javax.swing.JTable();
        nombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tEspectadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Nickname", "Correo Electonico", "Fecha de Nacimiento", "Cangeables"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tEspectadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tEspectadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tEspectadores);

        tRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha de registro", "Costro", "Estado", "Nombre de la funcion", "Fecha de la funcion", "Hora de inicio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tRegistros);

        nombre.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(nombre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tEspectadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tEspectadoresMouseClicked
        // TODO add your handling code here:
        
        int index = tEspectadores.getSelectedRow();
        nombre.setText(espectadores.get(index).getNombre());
        List<DtRegistro> registros=new ArrayList<DtRegistro>();
        registros=Fabrica.getCrlUsuarios().getRegistros(espectadores.get(index).getNickname());
        String matris[][] = new String [registros.size()][6];
        List<DtFuncion> funciones=new ArrayList<DtFuncion>();
        funciones=Fabrica.getCrlUsuarios().getFuncionesRegistros(espectadores.get(index).getNickname());
        
        for(int i=0; i<registros.size(); i++)
        {
            
            matris [i][0]=registros.get(i).getFecha().toString();
            matris [i][1]=Float.toString(registros.get(i).getCosto());
            matris [i][2]=registros.get(i).getEstado().toString();
            matris [i][3]=funciones.get(i).getNombre();
            matris [i][4]=funciones.get(i).getFecha().toString();
            matris [i][5]=funciones.get(i).getHoraInicio().toString();
            
        }
        tRegistros.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Fecha de registro", "Costro", "Estado", "Nombre de la funcion", "Fecha de la funcion", "Hora de inicio"
            }
        ));
    }//GEN-LAST:event_tEspectadoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarEspectadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarEspectadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarEspectadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarEspectadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarEspectadores().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombre;
    private javax.swing.JTable tEspectadores;
    private javax.swing.JTable tRegistros;
    // End of variables declaration//GEN-END:variables
}
